#!/bin/bash

source infrastructure/cli/_helpers/set-feature-environment

if [ -z "$FEATURE_ENVIRONMENT" ]; then
    echo "Cannot delete production database"
    exit 1
fi

source library/.venv/bin/activate
FEATURE_ENVIRONMENT_COLLECTIONS=$(python infrastructure/cli/_helpers/list_feature_database_collections.py)
if [ -z "$FEATURE_ENVIRONMENT_COLLECTIONS" ]; then
    echo "No collections found for feature environment $FEATURE_ENVIRONMENT"
fi

python infrastructure/cli/_helpers/delete_feature_database.py
