from collections.abc import Iterator, Mapping, Sequence
from typing import Any, Literal, overload

from redis.retry import Retry


class ConnectionPool:
    connection_kwargs: dict[str, Any]
    connection_class: type[Any]

    def __init__(
        self,
        *,
        connection_class: type[Any] = ...,
        host: str,
        port: int,
        db: int,
        decode_responses: bool,
        password: str | None = None,
        socket_timeout: float | None = None,
        socket_connect_timeout: float | None = None,
        health_check_interval: int = 0,
        retry: Retry | None = None,
        retry_on_timeout: bool = False,
        retry_on_error: list[type[Exception]] | None = None,
    ) -> None: ...


class Pipeline:
    def __init__(self, *, transaction: bool = False) -> None: ...
    
    def __enter__(self) -> "Pipeline": ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: object) -> None: ...
    
    def execute(self) -> Any: ...
    
    ## Key-Value (Strings)
    def get(self, name: str, /) -> "Pipeline": ...
    def set(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None, nx: bool | None = None, xx: bool | None = None) -> "Pipeline": ...
    def mget(self, names: Sequence[str], /) -> "Pipeline": ...
    def mset(self, mapping: Mapping[str, bytes], /, *, nx: bool | None = None, xx: bool | None = None) -> "Pipeline": ...
    def setnx(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None) -> "Pipeline": ...
    def incr(self, name: str, /) -> "Pipeline": ...
    def incrby(self, name: str, amount: int, /) -> "Pipeline": ...
    def decr(self, name: str, /) -> "Pipeline": ...
    def decrby(self, name: str, amount: int, /) -> "Pipeline": ...
    def delete(self, *names: str) -> "Pipeline": ...

    ## Hashes
    def hget(self, name: str, key: str, /) -> "Pipeline": ...
    def hset(self, name: str, /, *, mapping: Mapping[str, bytes]) -> "Pipeline": ...
    def hmget(self, name: str, keys: Sequence[str], /) -> "Pipeline": ...
    def hgetall(self, name: str, /) -> "Pipeline": ...
    def hdel(self, name: str, *keys: str) -> "Pipeline": ...
    def hincrby(self, name: str, key: str, amount: int, /) -> "Pipeline": ...

    ## Lists
    def lpush(self, name: str, *elements: bytes) -> "Pipeline": ...
    def rpush(self, name: str, *elements: bytes) -> "Pipeline": ...
    def lpop(self, name: str, /) -> "Pipeline": ...
    def rpop(self, name: str, /) -> "Pipeline": ...
    def lrange(self, name: str, start: int, stop: int, /) -> "Pipeline": ...
    def lindex(self, name: str, index: int, /) -> "Pipeline": ...
    def llen(self, name: str, /) -> "Pipeline": ...
        
    ## Sets
    def sadd(self, name: str, *members: bytes) -> "Pipeline": ...
    def srem(self, name: str, *members: bytes) -> "Pipeline": ...
    def smembers(self, name: str, /) -> "Pipeline": ...
    def sismember(self, name: str, member: bytes, /) -> "Pipeline": ...
    def smismember(self, name: str, /, *members: bytes) -> "Pipeline": ...
    def scard(self, name: str, /) -> "Pipeline": ...
    
    ## Sorted Sets
    def zadd(self, name: str, mapping: dict[bytes, float], /) -> "Pipeline": ...
    def zrem(self, name: str, *members: bytes) -> "Pipeline": ...
    def zrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> "Pipeline": ...
    def zrevrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> "Pipeline": ...
    def zscore(self, name: str, member: bytes, /) -> "Pipeline": ...
    def zcard(self, name: str, /) -> "Pipeline": ...
    def zremrangebyrank(self, name: str, start: int, stop: int, /) -> "Pipeline": ...
    def zincrby(self, name: str, amount: float, member: bytes, /) -> "Pipeline": ...

    # Key Management
    def expire(self, name: str, time: int, /) -> "Pipeline": ...
    def flushall(self) -> "Pipeline": ...

    # Scripting
    def eval(self, script: str, numkeys: int, *keys_and_args: bytes) -> "Pipeline": ...


class Redis:
    connection_pool: ConnectionPool

    def __init__(self, *, connection_pool: ConnectionPool) -> None: ...

    def pipeline(self, *, transaction: bool = False) -> Pipeline: ...

    ## Key-Value (Strings)
    def get(self, name: str, /) -> bytes | None: ...
    def set(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None, nx: bool | None = None, xx: bool | None = None) -> None: ...
    def mget(self, names: Sequence[str], /) -> list[bytes | None]: ...
    def mset(self, mapping: Mapping[str, bytes], /, *, nx: bool | None = None, xx: bool | None = None) -> None: ...
    def setnx(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None) -> bool: ...
    def incr(self, name: str, /) -> int: ...
    def incrby(self, name: str, amount: int, /) -> int: ...
    def decr(self, name: str, /) -> int: ...
    def decrby(self, name: str, amount: int, /) -> int: ...
    def delete(self, *names: str) -> int: ...

    ## Hashes
    def hget(self, name: str, key: str, /) -> bytes | None: ...
    @overload
    def hset(self, name: str, key: str | bytes, value: str | bytes, /) -> int: ...
    @overload
    def hset(self, name: str, /, *, mapping: Mapping[str, bytes]) -> int: ...
    def hmget(self, name: str, keys: Sequence[str], /) -> list[bytes | None]: ...
    def hgetall(self, name: str, /) -> dict[bytes, bytes]: ...
    def hdel(self, name: str, *keys: str) -> int: ...
    def hincrby(self, name: str, key: str, amount: int, /) -> int: ...

    ## Lists
    def lpush(self, name: str, *elements: bytes) -> int: ...
    def rpush(self, name: str, *elements: bytes) -> int: ...
    def lpop(self, name: str, /) -> bytes | None: ...
    def rpop(self, name: str, /) -> bytes | None: ...
    def lrange(self, name: str, start: int, stop: int, /) -> list[bytes]: ...
    def lindex(self, name: str, index: int, /) -> bytes | None: ...
    def llen(self, name: str, /) -> int: ...
        
    ## Sets
    def sadd(self, name: str, *members: bytes) -> int: ...
    def srem(self, name: str, *members: bytes) -> int: ...
    def smembers(self, name: str, /) -> set[bytes]: ...
    def sismember(self, name: str, member: bytes, /) -> bool: ...
    def smismember(self, name: str, /, *members: bytes) -> list[bool]: ...
    def scard(self, name: str, /) -> int: ...
    
    ## Sorted Sets
    def zadd(self, name: str, mapping: dict[bytes, float], /) -> int: ...
    def zrem(self, name: str, *members: bytes) -> int: ...
    @overload
    def zrange(self, name: str, start: int, stop: int, *, withscores: Literal[False] = False) -> list[bytes]: ...
    @overload
    def zrange(self, name: str, start: int, stop: int, *, withscores: Literal[True]) -> list[tuple[bytes, float]]: ...
    def zrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> list[bytes] | list[tuple[bytes, float]]: ...
    @overload
    def zrevrange(self, name: str, start: int, stop: int, *, withscores: Literal[False] = False) -> list[bytes]: ...
    @overload
    def zrevrange(self, name: str, start: int, stop: int, *, withscores: Literal[True]) -> list[tuple[bytes, float]]: ...
    def zrevrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> list[bytes] | list[tuple[bytes, float]]: ...
    def zscore(self, name: str, member: bytes, /) -> float | None: ...
    def zcard(self, name: str, /) -> int: ...
    def zremrangebyrank(self, name: str, start: int, stop: int, /) -> int: ...
    def zincrby(self, name: str, amount: float, member: bytes, /) -> float: ...

    # Key Management
    def expire(self, name: str, time: int, /) -> bool: ...
    def flushall(self) -> None: ...

    # Scanning
    def scan(self, cursor: int = 0, *, match: str | None = None, count: int | None = None) -> tuple[int, list[str]]: ...
    def scan_iter(self, *, match: str | None = None, count: int | None = None) -> Iterator[str]: ...

    # Server / dump-restore
    def ping(self) -> bool: ...
    def dump(self, name: str, /) -> bytes | None: ...
    def pttl(self, name: str, /) -> int: ...
    def restore(self, name: str, ttl: int, value: bytes, /, *, replace: bool = False) -> None: ...

    # Scripting
    def eval(self, script: str, numkeys: int, *keys_and_args: bytes) -> Any: ...