class AbstractBackoff:
    def reset(self) -> None: ...
    def compute(self, failures: int) -> float: ...


class ExponentialBackoff(AbstractBackoff):
    def __init__(self, cap: float = ..., base: float = ...) -> None: ...
