#!/bin/bash

source infrastructure/cli/_helpers/set-feature-environment
source infrastructure/cli/provider/helpers/environment-resources

if [ -z "$FEATURE_ENVIRONMENT" ]; then
    echo "Cannot communicate with production storage"
    exit 1
fi

load_blob_environment || exit 1

source library/providers/azure/.venv/bin/activate
python infrastructure/cli/_helpers/clear_feature_storage.py
