/**
 * Query key factory for consistent cache key management.
 * Keys match the format generated by openapi-react-query: [method, path, init?]
 * Use these keys in both query options and mutation invalidations.
 */
export const queryKeys = {
  notes: {
    base: () => ["get", "/rest/notes/notes"] as const,
  },
};
