#!/bin/bash

terraform_output() {
    local folder=$1
    local name=$2
    local value

    pushd infrastructure/terraform/configurations/"$folder" >/dev/null || return 1
    if [ ! -d ".terraform" ]; then
        terraform init >/dev/null
    fi
    value=$(TF_WORKSPACE="${FEATURE_ENVIRONMENT:-default}" terraform output -json "$name" 2>/dev/null) || value=
    popd >/dev/null || return 1

    echo "$value"
}
