steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t $_TAG \
          -f infrastructure/docker/admin/Dockerfile \
          --build-arg FEATURE_ENVIRONMENT=$_FEATURE_ENVIRONMENT \
          --cache-from type=registry,ref=$_CACHE_TAG \
          --cache-from type=registry,ref=$_TAG \
          --cache-to type=registry,ref=$_CACHE_TAG,mode=max \
          .
substitutions:
  _FEATURE_ENVIRONMENT: ''
  _TAG: ''
  _CACHE_TAG: ''
options:
  machineType: E2_MEDIUM
  logging: CLOUD_LOGGING_ONLY
