#!/bin/bash
set -e

source infrastructure/cli/_helpers/set-feature-environment
source infrastructure/cli/provider/helpers/acr-login

acr_login

TAG="${CONTAINER_REGISTRY}/${FEATURE_ENVIRONMENT}admin:main"
CACHE_TAG="${CONTAINER_REGISTRY}/docker-cache:admin-main"

echo "Building the admin image for the ${FEATURE_ENVIRONMENT:-production} environment..."

infrastructure/docker/provider/admin/build "$TAG" "$CACHE_TAG"
