#!/bin/bash
set -e

source infrastructure/cli/_helpers/set-feature-environment

TAG="us-central1-docker.pkg.dev/$GOOGLE_CLOUD_PROJECT/${FEATURE_ENVIRONMENT}admin/admin:main"
CACHE_TAG="us-central1-docker.pkg.dev/$OPERATIONS_PROJECT_ID/docker-cache/admin:main"

echo "Building the admin image for the ${FEATURE_ENVIRONMENT:-production} environment..."

gcloud builds submit \
    --config infrastructure/docker/admin/cloudbuild.yaml \
    --substitutions _FEATURE_ENVIRONMENT=$FEATURE_ENVIRONMENT,_TAG=$TAG,_CACHE_TAG=$CACHE_TAG \
    --project $GOOGLE_CLOUD_PROJECT \
    --region us-central1 \
    --service-account projects/$GOOGLE_CLOUD_PROJECT/serviceAccounts/${FEATURE_ENVIRONMENT}cloud-build@$GOOGLE_CLOUD_PROJECT.iam.gserviceaccount.com \
    --polling-interval=5 \
    .
