#!/bin/bash

source infrastructure/cli/_helpers/set-feature-environment
source infrastructure/cli/provider/helpers/environment-resources

PROFILE=$(front_door_profile_name) || exit 1

ENDPOINTS=$(az afd endpoint list \
    --profile-name "$PROFILE" \
    --resource-group "$AZURE_RESOURCE_GROUP" \
    --query '[].name' \
    --output tsv)

for ENDPOINT in $ENDPOINTS; do
    [[ "$ENDPOINT" == *api ]] || continue
    echo ${ENDPOINT%api}
done
