#!/bin/bash
set -e
OPTIND=1
NUM_ATTEMPTS=1
AUTO_APPROVE_FLAG=
FOLDER=
OPERATION=
TARGET=
while getopts ":f:o:t:a:" opt; do
  case ${opt} in
    f )
        FOLDER=$OPTARG
        ;;
    o )
        OPERATION=$OPTARG
        if [ "$OPERATION" != "plan" ] && [ "$OPERATION" != "apply" ] && [ "$OPERATION" != "destroy" ]
        then
          echo "Invalid operation. Please use plan, apply or destroy"
          exit 1
        fi
        if [ "$OPERATION" != "plan" ]
        then
          AUTO_APPROVE_FLAG="--auto-approve"
        fi
        ;;
    t )
        TARGET=$OPTARG
        ;;
    a )
        NUM_ATTEMPTS=$OPTARG
        ;;
    \? )
        echo "Usage: run-terraform -f <folder> -o <operation> -t <target>"
        exit 1
        ;;
  esac
done

if [ -z "$FOLDER" ] || [ -z "$OPERATION" ]; then
    echo "Error: folder (-f) and operation (-o) are required"
    echo "Usage: run-terraform -f <folder> -o <operation> [-t <target>] [-a <attempts>]"
    exit 1
fi

cd infrastructure/terraform/configurations/$FOLDER

echo "Initializing Terraform..."
terraform init

if [[ -z "$FEATURE_ENVIRONMENT" || "$FOLDER" == "operations" ]]
then
    terraform workspace select default
else
    terraform workspace select -or-create "$FEATURE_ENVIRONMENT"
fi

echo "Running terraform $OPERATION for $FOLDER..."

SUCCESS=0
echo "NUM ATTEMPTS = $NUM_ATTEMPTS"
for attempt in $(seq 1 $NUM_ATTEMPTS)
do
  if [[ -n "$TARGET" ]]
  then
    if terraform $OPERATION $AUTO_APPROVE_FLAG -target $TARGET; then
      SUCCESS=1
      break
    fi
  else
    if terraform $OPERATION $AUTO_APPROVE_FLAG; then
      SUCCESS=1
      break
    fi
  fi
  echo "Failed to run terraform $OPERATION for $FOLDER. Attempt $attempt"
  if [ $attempt -ne $NUM_ATTEMPTS ]; then
    sleep 3
  fi
done

if [ $SUCCESS -eq 0 ]; then
  echo "Failed to run terraform $OPERATION for $FOLDER after $NUM_ATTEMPTS attempts"
  exit 1
fi

cd -
