[project]
name = "notes-service"
version = "0.0.0"
description = "The Notes Service records notes written by members of an organization and summarizes them."
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "library",
]

[tool.uv.sources]
library = { path = "../../library" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=0.25.3",
    "pytest-mock>=3.14.0",
]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::SyntaxWarning",
    "ignore:pkg_resources is deprecated:UserWarning",
]
testpaths = ["tests"]
asyncio_mode = "auto"

[project.scripts]
run-server-rest = "notes_service.presentation.servers.rest.app:main"

run-pool-executors = "notes_service.presentation.pools.executors:main"
run-pool-listeners = "notes_service.presentation.pools.listeners:main"
run-pool-triggers = "library.presentation.service.triggers.pool:main"

run-job-purge-notes = "notes_service.presentation.jobs.purge_notes:main"
