operations_project_id = "acme-operations-155d"
preferred_region      = "us-central1"
domain_name           = "acme.mentionai.app"
admin_subdomain       = "admin"
dns_managed_zone      = "acme"
python_warnings       = "ignore::DeprecationWarning:authlib\\._joserfc_helpers"
