#!/bin/bash

source infrastructure/cli/_helpers/set-feature-environment

if [ -z "$FEATURE_ENVIRONMENT" ]; then
    echo "Cannot destroy production environment"
    exit 1
fi

# Clear all data before destroying infrastructure
source infrastructure/cli/deployment/clear-feature-environment/clerk
source infrastructure/cli/deployment/clear-feature-environment/database

# Then destroy infrastructure
source infrastructure/cli/deployment/run-terraform -f admin -o destroy
OPTIND=1
source infrastructure/cli/deployment/run-terraform -f services -o destroy
OPTIND=1
source infrastructure/cli/deployment/run-terraform -f web -o destroy
OPTIND=1
source infrastructure/cli/deployment/run-terraform -f mcp -o destroy
