#!/bin/bash

URL_MAPS=$(gcloud compute url-maps list \
    --project=$GOOGLE_CLOUD_PROJECT \
    --format="get(name)")

for URL_MAP in $URL_MAPS; do
    [[ "$URL_MAP" == *mcp-url-map ]] && continue
    FEATURE_ENVIRONMENT_NAME=$(echo $URL_MAP | sed 's/api-url-map$//')
    echo $FEATURE_ENVIRONMENT_NAME
done