from collections.abc import Mapping, Sequence
from typing import Any, Literal, overload

from redis.asyncio.retry import Retry


class ConnectionPool:
    connection_kwargs: dict[str, Any]
    connection_class: type[Any]

    def __init__(
        self,
        *,
        connection_class: type[Any] = ...,
        host: str,
        port: int,
        db: int,
        decode_responses: bool,
        password: str | None = None,
        socket_timeout: float | None = None,
        socket_connect_timeout: float | None = None,
        health_check_interval: int = 0,
        retry: Retry | None = None,
        retry_on_timeout: bool = False,
        retry_on_error: list[type[Exception]] | None = None,
    ) -> None: ...
    async def aclose(self) -> None: ...


class CMSCommands:
    async def initbydim(self, key: str, width: int, depth: int) -> bool: ...
    async def incrby(self, key: str, items: Sequence[bytes], increments: Sequence[int]) -> list[int]: ...
    async def query(self, key: str, *items: bytes) -> list[int]: ...
    async def info(self, key: str) -> dict[str, Any]: ...


class CMSPipelineCommands:
    def initbydim(self, key: str, width: int, depth: int) -> "Pipeline": ...
    def incrby(self, key: str, items: Sequence[bytes], increments: Sequence[int]) -> "Pipeline": ...
    def query(self, key: str, *items: bytes) -> "Pipeline": ...


class Pipeline:
    def __init__(self, *, transaction: bool = False) -> None: ...
    
    async def __aenter__(self) -> "Pipeline": ...
    async def __aexit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: object) -> None: ...
    
    async def execute(self) -> Any: ...

    ## Count-Min Sketch (RedisBloom)
    def cms(self) -> CMSPipelineCommands: ...
    
    ## Key-Value (Strings)
    def get(self, name: str, /) -> "Pipeline": ...
    def set(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None, nx: bool | None = None, xx: bool | None = None) -> "Pipeline": ...
    def mget(self, names: Sequence[str], /) -> "Pipeline": ...
    def mset(self, mapping: Mapping[str, bytes], /, *, nx: bool | None = None, xx: bool | None = None) -> "Pipeline": ...
    def setnx(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None) -> "Pipeline": ...
    def incr(self, name: str, /) -> "Pipeline": ...
    def incrby(self, name: str, amount: int, /) -> "Pipeline": ...
    def decr(self, name: str, /) -> "Pipeline": ...
    def decrby(self, name: str, amount: int, /) -> "Pipeline": ...
    def delete(self, *names: str) -> "Pipeline": ...

    ## Hashes
    def hget(self, name: str, key: str, /) -> "Pipeline": ...
    def hset(self, name: str, /, *, mapping: Mapping[str, bytes]) -> "Pipeline": ...
    def hmget(self, name: str, keys: Sequence[str], /) -> "Pipeline": ...
    def hgetall(self, name: str, /) -> "Pipeline": ...
    def hdel(self, name: str, *keys: str) -> "Pipeline": ...
    def hincrby(self, name: str, key: str, amount: int, /) -> "Pipeline": ...

    ## Lists
    def lpush(self, name: str, *elements: bytes) -> "Pipeline": ...
    def rpush(self, name: str, *elements: bytes) -> "Pipeline": ...
    def lpop(self, name: str, /) -> "Pipeline": ...
    def rpop(self, name: str, /) -> "Pipeline": ...
    def lrange(self, name: str, start: int, stop: int, /) -> "Pipeline": ...
    def lindex(self, name: str, index: int, /) -> "Pipeline": ...
    def llen(self, name: str, /) -> "Pipeline": ...
        
    ## Sets
    def sadd(self, name: str, *members: bytes) -> "Pipeline": ...
    def srem(self, name: str, *members: bytes) -> "Pipeline": ...
    def smembers(self, name: str, /) -> "Pipeline": ...
    def sismember(self, name: str, member: bytes, /) -> "Pipeline": ...
    def smismember(self, name: str, /, *members: bytes) -> "Pipeline": ...
    def scard(self, name: str, /) -> "Pipeline": ...
    
    ## Sorted Sets
    def zadd(self, name: str, mapping: dict[bytes, float], /) -> "Pipeline": ...
    def zrem(self, name: str, *members: bytes) -> "Pipeline": ...
    def zrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> "Pipeline": ...
    def zrevrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> "Pipeline": ...
    def zscore(self, name: str, member: bytes, /) -> "Pipeline": ...
    def zcard(self, name: str, /) -> "Pipeline": ...
    def zremrangebyrank(self, name: str, start: int, stop: int, /) -> "Pipeline": ...
    def zremrangebyscore(self, name: str, min: float | str, max: float | str, /) -> "Pipeline": ...
    def zincrby(self, name: str, amount: float, member: bytes, /) -> "Pipeline": ...

    # Key Management
    def expire(self, name: str, time: int, /) -> "Pipeline": ...
    def flushall(self) -> "Pipeline": ...

    # Scripting
    def eval(self, script: str, numkeys: int, *keys_and_args: bytes) -> "Pipeline": ...


class Redis:
    connection_pool: ConnectionPool

    def __init__(self, *, connection_pool: ConnectionPool) -> None: ...

    def pipeline(self, *, transaction: bool = False) -> Pipeline: ...
    async def aclose(self) -> None: ...

    ## Key-Value (Strings)
    async def get(self, name: str, /) -> bytes | None: ...
    async def set(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None, nx: bool | None = None, xx: bool | None = None) -> bool | None: ...
    async def mget(self, names: Sequence[str], /) -> list[bytes | None]: ...
    async def mset(self, mapping: Mapping[str, bytes], /, *, nx: bool | None = None, xx: bool | None = None) -> None: ...
    async def setnx(self, name: str, value: bytes, /, *, ex: int | None = None, px: int | None = None) -> bool: ...
    async def incr(self, name: str, /) -> int: ...
    async def incrby(self, name: str, amount: int, /) -> int: ...
    async def decr(self, name: str, /) -> int: ...
    async def decrby(self, name: str, amount: int, /) -> int: ...
    async def delete(self, *names: str) -> int: ...

    ## Hashes
    async def hget(self, name: str, key: str, /) -> bytes | None: ...
    async def hset(self, name: str, /, *, mapping: Mapping[str, bytes]) -> int: ...
    async def hmget(self, name: str, keys: Sequence[str], /) -> list[bytes | None]: ...
    async def hgetall(self, name: str, /) -> dict[bytes, bytes]: ...
    async def hdel(self, name: str, *keys: str) -> int: ...
    async def hincrby(self, name: str, key: str, amount: int, /) -> int: ...

    ## Lists
    async def lpush(self, name: str, *elements: bytes) -> int: ...
    async def rpush(self, name: str, *elements: bytes) -> int: ...
    async def lpop(self, name: str, /) -> bytes | None: ...
    async def rpop(self, name: str, /) -> bytes | None: ...
    async def lrange(self, name: str, start: int, stop: int, /) -> list[bytes]: ...
    async def lindex(self, name: str, index: int, /) -> bytes | None: ...
    async def llen(self, name: str, /) -> int: ...
        
    ## Sets
    async def sadd(self, name: str, *members: bytes) -> int: ...
    async def srem(self, name: str, *members: bytes) -> int: ...
    async def smembers(self, name: str, /) -> set[bytes]: ...
    async def sismember(self, name: str, member: bytes, /) -> bool: ...
    async def smismember(self, name: str, /, *members: bytes) -> list[bool]: ...
    async def scard(self, name: str, /) -> int: ...
    
    ## Sorted Sets
    async def zadd(self, name: str, mapping: dict[bytes, float], /) -> int: ...
    async def zrem(self, name: str, *members: bytes) -> int: ...
    @overload
    async def zrange(self, name: str, start: int, stop: int, *, withscores: Literal[False] = False) -> list[bytes]: ...
    @overload
    async def zrange(self, name: str, start: int, stop: int, *, withscores: Literal[True]) -> list[tuple[bytes, float]]: ...
    async def zrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> list[bytes] | list[tuple[bytes, float]]: ...
    @overload
    async def zrevrange(self, name: str, start: int, stop: int, *, withscores: Literal[False] = False) -> list[bytes]: ...
    @overload
    async def zrevrange(self, name: str, start: int, stop: int, *, withscores: Literal[True]) -> list[tuple[bytes, float]]: ...
    async def zrevrange(self, name: str, start: int, stop: int, *, withscores: bool = False) -> list[bytes] | list[tuple[bytes, float]]: ...
    async def zscore(self, name: str, member: bytes, /) -> float | None: ...
    async def zcard(self, name: str, /) -> int: ...
    async def zremrangebyrank(self, name: str, start: int, stop: int, /) -> int: ...
    async def zremrangebyscore(self, name: str, min: float | str, max: float | str, /) -> int: ...
    async def zincrby(self, name: str, amount: float, member: bytes, /) -> float: ...

    # Key Management
    async def expire(self, name: str, time: int, /) -> bool: ...
    async def flushall(self) -> None: ...

    # Scanning
    async def scan(self, cursor: int = 0, *, match: str | None = None, count: int | None = None) -> tuple[int, list[str]]: ...

    # Scripting
    async def eval(self, script: str, numkeys: int, *keys_and_args: bytes) -> Any: ...

    ## Count-Min Sketch (RedisBloom)
    def cms(self) -> CMSCommands: ...