steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        docker buildx create --use
        docker buildx build \
          --platform linux/amd64 \
          --push \
          -t $_TAG \
          -f infrastructure/docker/mcp/Dockerfile \
          .
substitutions:
  _TAG: ''
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
