#!/bin/bash

get_feature_instance_ip() {
    local instance_name=$1
    local project=${2:-${GOOGLE_CLOUD_PROJECT:-acme-feature-0000}}

    gcloud compute instances list \
        --project="${project}" \
        --filter="name=${instance_name}" \
        --format='get(networkInterfaces[0].accessConfigs[0].natIP)' \
        --limit=1
}

get_feature_instance_zone() {
    local instance_name=$1
    local project=${2:-${GOOGLE_CLOUD_PROJECT:-acme-feature-0000}}

    gcloud compute instances list \
        --project="${project}" \
        --filter="name=${instance_name}" \
        --format='value(zone.basename())' \
        --limit=1
}

get_feature_mig_zone() {
    local mig_name=$1
    local project=${2:-${GOOGLE_CLOUD_PROJECT:-acme-feature-0000}}

    gcloud compute instance-groups managed list \
        --project="${project}" \
        --filter="name=${mig_name}" \
        --format='value(zone.basename())' \
        --limit=1
}
