#!/bin/bash

source infrastructure/cli/_helpers/connect-to-feature-environment

if [ -z "$FEATURE_ENVIRONMENT" ]; then
    echo "Cannot communicate with production cache"
    exit 1
fi

source library/.venv/bin/activate
python infrastructure/cli/_helpers/list_feature_cache_keys.py
